### ISSUE TITLE
Please create additional "good first issues" to reach the suggested minimum of 15 by 9/15.

### ISSUE THREAD

**Issue by rednaksi91** [opensearch-project/opensearch-benchmark-workloads#118]
Open Source Contributor Initiative (OSCI) launches on September 20th. Java client repo lacks the minimum of 15 "good first issues" that can be picked up by participants of OSCI.

Please create additional "good first issues" to reach the suggested minimum of 15 by 9/15.

**Comment by gkamat** [comment]
We will add a few more, however this is a workload repository, not a code repo, so hitting 15 will not be straightforward.  This repository should be considered in conjunction with the OpenSearch Benchmark one, which will have most of the "good first issues".

**Comment by IanHoang** [comment]
The issue #120 can be applied to each workload. We have asked some OSCI members to tackle this issue per workload. With this in mind, I'll create rework #120 to be a meta issue and create a child issue related to this per workload
