### ISSUE TITLE
[BUG] Workloads do not map target throughput correctly when set to zero

### ISSUE THREAD

**Issue by gkamat** [opensearch-project/opensearch-benchmark-workloads#119]
### What is the bug?
For many workloads, the test-procedure defaults include a fragment like so:
```
          {%- if not target_throughput %}
          ,"target-throughput": 50
          {%- elif target_throughput is string and target_throughput.lower() == 'none' %}
          {%- else %}
          ,"target-throughput": {{ target_throughput | tojson }}
          {%- endif %}
```

When the target throughput is set to 0, instead of disabling the target throughput as would normally occur, it gets set to 50.  The mechanism to disable it is to set it to `none`, which is not the normal convention in OSB.

The change above is a consequence of `f9f24c6d`, which should be reverted.

**Comment by IanHoang** [comment]
New versions should work as many users have been using `0`. Closing this out for now.
