### ISSUE TITLE
SO: Add configurable throughput and client parameters per operation 

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark-workloads#125]
Child issue of https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/120 issue. Add configurable throughput and client parameters per operation for so workload

**Comment by OVI3D0** [comment]
Hey @IanHoang I'll take this one

**Comment by IanHoang** [comment]
There are no configurable throughput or search client params here. Will close
