### ISSUE TITLE
[FEATURE]  Add new workload to test performance of knn_vector field type

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-benchmark-workloads#140]
### Is your feature request related to a problem?
OpenSearch KNN plugin hosts workloads  here(https://github.com/opensearch-project/k-NN/tree/main/benchmarks/osb) to run benchmarks for every release. We would like to move it to this repository so that all workloads can be in one place and  will get more visibility. 

### What solution would you like?
Create a new workload to run workloads using knn_vector to measure vector search performance.

### What alternatives have you considered?
N/A

### Do you have any additional context?
N/A

**Comment by gkamat** [comment]
This would be very helpful for KNN users.  Please add the workloads to the repository and raise a PR.  Thanks.
