### ISSUE TITLE
[FEATURE] Add new corpora with sift-128-l2 dataset for vector search workload

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/opensearch-benchmark-workloads#150]
### Is your feature request related to a problem?
For vector search workload, we need to provide sample dataset for benchmark testing. We will start with sift-128-l2-1M dataset. We have this dataset in our s3 bucket. I can share this dataset so that it can be available behind cloud front for download as corpora.

### What solution would you like?
Download vector search dataset and consider it as dataset for knn vector search workload

### What alternatives have you considered?
Manually download dataset outside benchmarks,

### Do you have any additional context?
This is required as part of #140

**Comment by VijayanB** [comment]
This is required for 2.12

**Comment by gkamat** [comment]
Please provide details on where the data corpus is available and whether it is appropriately licensed.  If so, we can add it to the standard corpus repository.

**Comment by VijayanB** [comment]
@gkamat  Sure. I shared those details and gave permission to download that dataset from our repository to @IanHoang . Thanks
