### ISSUE TITLE
[PROPOSAL] Adding capabilities to introduce randomness in workload queries

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/opensearch-benchmark-workloads#152]
### What are you proposing?

As of now, opensearch workload mostly deals with static queries ie the values are fixed. For example in nyc_taxis(search recommended workload), we have a set of static queries which we use to perform benchmark. But this doesn't help in simulating real world scenarios where data distribution and access patterns are not predictable. Plus there is not way to use nyc_taxis to run test with caches(like request cache) turned on. 

But considering we have features like Tiered caching coming up([link](https://github.com/opensearch-project/OpenSearch/issues/10024)), we need capabilities to generate some workload with some dynamic queries(randomization in values) so that we can test with cache turned on as well. We wrote some custom logic on top of nyc_taxis to create some randomization.

I recommend to have a parameter via which we can introduce some randomization in nyc_taxis(for example) query values which would be useful:
1. To perform benchmark with caches turned on. Via this parameter we can generate desired cache hits/misses.
2. To have some kind of randomization in workload so that it not very predictable.

We can have a parameter via which users can generate X number of repeated queries and rest unique queries. Where X>=0.

This parameter can be enabled on a demand basis if needed. I believe it might also help other workloads as well and not just nyc_taxis.

### What users have asked for this feature?
We will need this as part of Tiered caching ([link](https://github.com/opensearch-project/OpenSearch/issues/10024)) and would be useful to others as well.

### What problems are you trying to solve?
To introduce a capability to have some randomization in workload queries.

### What is the developer experience going to be?
We will introduce a parameter in the workload which can control the extent of randomization within workload queries.

#### Are there any security considerations? 
_Describe if the feature has any security considerations or impact. What is the security model of the new APIs? Features should be integrated into the OpenSearch security suite and so if they are not, we should highlight the reasons here._

#### Are there any breaking changes to the API
No.

### What is the user experience going to be?
They can enable this feature via a parameter.

#### Are there breaking changes to the User Experience?
No

### Why should it be built? Any reason not to?
_Describe the value that this feature will bring to the OpenSearch community, as well as what impact it has if it isn't built, or new risks if it is. Highlight opportunities for additional research._

### What will it take to execute?
_Describe what it will take to build this feature. Are there any assumptions you may be making that could limit scope or add limitations? Are there performance, cost, or technical constraints that may impact the user experience? Does this feature depend on other feature work? What additional risks are there?_

### Any remaining open questions?
_What are known enhancements to this feature? Any enhancements that may be out of scope but that we will want to track long term? List any other open questions that may need to be answered before proceeding with an implementation._

**Comment by sgup432** [comment]
@gkamat

**Comment by peteralfonsi** [comment]
I implemented a version of this in [my fork](https://github.com/peteralfonsi/opensearch-benchmark-workloads/tree/final/modified_nyc_taxis) of OSB-workloads, which we used for tiered caching benchmarking. 

Each query (the same as the nyc_taxis queries, except for the values in the ranges) is defined in workload.py. Each one has a function that provides random range values, defined in query_value_providers.py. When the query functions are actually run, they use the helper function get_values(), which takes in a parameter repeat_freq that comes in from the command line. If repeat_freq = 0.3, there's a 30% chance of using a repeated value. 

To achieve this, before the workload starts, we use the query value provider functions to save many randomly generated "standard values" for each query type to a file. (This is done in generate_standard_values.py). Then we would return one of these standard values through get_values(). (Deciding which exact one we return is a bit complicated and needs to be tweaked to be more general - we currently have it hardcoded for our use case). Depending on how this is done, there's a high chance this value has been seen before in the workload, so it could be a cache hit. 

In the other 70% of cases, we use the query value provider function to generate fresh values. For most query types, these are times with second-level granularity, so the chance of this value being seen before is very low.

**Comment by gkamat** [comment]
This is certainly a useful and needed capability for OSB.  We may want to open an RFC to look at different options to do this and if support within OSB rather than separately in each workload would be the appropriate path forward.

**Comment by sgup432** [comment]
@gkamat Sure, we ideally wanted it to be implemented in a way so that it can reused across workloads. For a start, nyc_taxis could utilize it.
I can open a RFC at OSB level itself then and have a discussion there as well on this.

**Comment by IanHoang** [comment]
This has been completed in https://github.com/opensearch-project/opensearch-benchmark/issues/443. Closing issue
