### ISSUE TITLE
[BUG] Using "so" workload outputs Error

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark-workloads#22]
**What is the bug?**
When using the SO workload, OpenSearch-Benchmark outputs a syntax error in the console.

**How can one reproduce the bug?**
1. Install OpenSearch-Benchmark
2. Run a benchmark command that invokes the workload "so". (i.e. `opensearch-benchmark info --workload so`). 
3. See error

**What is the expected behavior?**

**What is your host/environment?**
 - OS: [Linux & Darwin]
 - Version [0.0.1]
 - Plugins [ None ]

**Do you have any screenshots?**
<img width="1473" alt="Screen Shot 2021-12-20 at 11 35 36 AM" src="https://user-images.githubusercontent.com/51065478/146808744-0e468e36-077c-4067-8044-32b78c68d1e0.png">

**Comment by travisbenedict** [comment]
Fixed in https://github.com/opensearch-project/opensearch-benchmark-workloads/pull/23
