### ISSUE TITLE
[FEATURE] Add recall calculation as part of benchmark summary for vectorsearch workloads.

### ISSUE THREAD

**Issue by akashsha1** [opensearch-project/opensearch-benchmark-workloads#282]
### Is your feature request related to a problem?
Vector search workloads presently do not support recall calculation in the summary section.

### What solution would you like?
VectorSearch outcomes rely on recall, which is an important metric in determining if the search was successful. It would be ideal to include this metric, as new workloads and benchmarks in this space evolve (e.g. semantic search)

### What alternatives have you considered?
The current alternative is to manually calculate the recall offline based on the data being published, or using opensearch queries to aggregrate the information.

**Comment by gkamat** [comment]
Will look into this issue further shortly, whether this could be just another metric that is reported.
