### ISSUE TITLE
[README] Add contribution guide reference to README

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark-workloads#293]
To streamline the contribution experience, we should add the official contribution guide to the README so that users can reference it when creating PRs: https://opensearch.org/docs/latest/benchmark/user-guide/contributing-workloads/

**Comment by safimuhammad** [comment]
hey, can I get this one done?

**Comment by IanHoang** [comment]
@safimuhammad Yes! Feel free to cut out a PR for this and tag any maintainer to review

**Comment by safimuhammad** [comment]
Thanks alot.
