### ISSUE TITLE
[FEATURE] VectorSearch - Ability to control target-throughput and time-period

### ISSUE THREAD

**Issue by mcm2100** [opensearch-project/opensearch-benchmark-workloads#317]
### Is your feature request related to a problem?
When running VectorSearch workload tests for AOSS collections, I am unable to set target-throughput for Indexing and Search operations as I am for other workloads. Additionally, I am unable to specify a time-period for the workload to run for longer running tests. This leads my VectorSearch OSB tests to be unreliable as both the traffic and test duration are unable to be set granularly.

### What solution would you like?
I would like to be able to set these test properties for VectorSearch workloads as I can in other AOSS workload tests so that target-throughput and time-period can be set explicitly.

**Comment by mcm2100** [comment]
I am able to side step these issues myself by manually editing the opensearch-benchmark-workloads package myself to expose 'target-throughput' and manually add 'repetitions' to simulate extending test duration. But would like these to be readily available parameters without needing to adjust source code

**Comment by gkamat** [comment]
This is a reasonable expectation.  We should enhance the workload with this capability.  @VijayanB, what do you think?

**Comment by VijayanB** [comment]
Thanks for raising this issue. It will definitely add value to vector search. Please feel free to contribute.
