### ISSUE TITLE
[FEATURE] Simplify target-throughput and search clients parameters across all workloads

### ISSUE THREAD

**Issue by IanHoang** [opensearch-project/opensearch-benchmark-workloads#318]
### Is your feature request related to a problem?
Currently, many of the workloads still use this old jinja2 format to interpret parameters target-throughput and search clients. This is more verbose than necessary and users have expressed interest in making a uniformed and simplified version across all workloads.
```
          "warmup-iterations": 100,
          "iterations": 100
          {%- if not target_throughput %}
          ,"target-throughput": 1
          {%- elif target_throughput is string and target_throughput.lower() == 'none' %}
          {%- else %}
          ,"target-throughput": {{ target_throughput | tojson }}
          {%- endif %}
          {%-if search_clients is defined and search_clients %}
          ,"clients": {{ search_clients | tojson}}
          {%- endif %}
```

### What solution would you like?
Make rest of the workloads look similar to Big5 and percolator. Target-throughput can be disabled if users specify an empty string ("") or 0.
```
  "warmup-iterations": {{ warmup_iterations | default(200) | tojson }},
  "iterations": {{ test_iterations | default(100) | tojson }},
  "target-throughput": {{ target_throughput | default(2) | tojson }},
  "clients": {{ search_clients | default(1) }}
```

**Comment by gkamat** [comment]
@OVI3D0 you may want to take this up.  Thanks.

**Comment by OVI3D0** [comment]
@gkamat yes I'll take it👍

**Comment by IanHoang** [comment]
This is complete
