### ISSUE TITLE
Remove mapping types

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-benchmark-workloads#37]
As part of v2.0 release, `mapping types` are getting removed from OpenSearch engine. Below are the changes in the opensearch-engine.
- Removal of type from rest end-points
- Removal of include_type_name parameter from API requests.

As part of this issue, please verify if type removal change on OpenSearch engine impacts this repository. If yes, then please remove the type references/usage from this plugin. 

Related: [OpenSearch-engine meta issue](https://github.com/opensearch-project/opensearch/issues/1940)

**Comment by dreamer-89** [comment]
This change goes in `v2.0.0` release in OpenSearch repository and is a `breaking` change. Request maintainer to add appropriate labels.

**Comment by travisbenedict** [comment]
This repository is not impacted this change.
