### ISSUE TITLE
[FEATURE] Expose "iterations" as workload-params

### ISSUE THREAD

**Issue by gashutos** [opensearch-project/opensearch-benchmark-workloads#388]
https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/nyc_taxis/test_procedures/default.json#L59

Like mentioned above, each OSB query has hardcoded number of iterations and they are not exposed as workload-params. Can we expose it as workload-params so that outside use can have better fine graned control over high throughput tests where we can have millions of iterations.

**Comment by IanHoang** [comment]
Closing this in favor of this duplicate issue: https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/393
