### ISSUE TITLE
[FEATURE] Add configurable `iterations` parameters per operation

### ISSUE THREAD

**Issue by OVI3D0** [opensearch-project/opensearch-benchmark-workloads#393]
### What solution would you like?
Similar to #120 , workloads should also have configurable iteration parameters per operation. This is would help for OSB's new [Aggregate](https://github.com/opensearch-project/opensearch-benchmark/pull/638) command. In the event where users customize the amount of iterations they want certain operations to run, the aggregate command should then be able to take these custom values into consideration when performing the calculation for the aggregated results.

Updating the workloads to use something like this could help:
```
        {
          "operation": "default",
          "warmup-iterations": {{ default_warmup_iterations or warmup_iterations | default(50) | tojson }},
          "iterations": {{ default_iterations or iterations | default(100) | tojson }},
          "target-throughput": {{ default_target_throughput or target_throughput | default(3) | tojson }},
          "clients": {{ default_clients or search_clients | default(1) }}
        }
```

- [x] nyc_taxis #394 
- [x] http_logs #395 
- [x] so #396 
- [x] geonames #397 
- [x] geoshape #398 
- [x] geopoint #399 
- [x] geopointshape #400 
- [x] eventdata #401 
- [x] pmc #402 
- [x] percolator #403 
- [x] noaa #404 
- [x] nested #405

**Comment by IanHoang** [comment]
Two things left
### Remaining iterations:
- Geonames: 
    - Branch 7: https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/7/geonames/test_procedures/default.json#L451-L504
    - Main Branch: https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/geonames/test_procedures/default.json#L450-L472

### Fix default_warmup_iterations and default_iterations
Some parameters have incorrectly named parameters. Example: https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/main/http_logs/test_procedures/default.json#L832-L923

**Comment by IanHoang** [comment]
Thanks for the help @OVI3D0 !
