### ISSUE TITLE
[BUG] Incorrect information in workload READMEs

### ISSUE THREAD

**Issue by travisbenedict** [opensearch-project/opensearch-benchmark-workloads#45]
### What is the bug?
READMEs for the workloads include the following line

>This workload allows to overwrite the following parameters with Benchmark 0.8.0+ using --workload-params:

Source: https://github.com/opensearch-project/opensearch-benchmark-workloads/tree/main/eventdata#parameters

Workload params are supported in all version of Benchmark so this line should be updated to reflect that.

### Do you have any additional context?
The 0.8.0+ is a holdover from when Benchmark was forked from Rally

**Comment by IanHoang** [comment]
Addressed in this older PR https://github.com/opensearch-project/opensearch-benchmark-workloads/commit/5f7a771cfbca4fee9fc6d238cb81f0b6157abb62
