### ISSUE TITLE
Missing MAINTAINERS.md file

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/opensearch-benchmark-workloads#53]
During an evaluation of our repos last week, I noticed this repository does not contain a MAINTAINERS.md file. Our https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md file provides an overview and outline to resolve this.

**Comment by treddeni-amazon** [comment]
@achitojha Could you add a maintainers file for this repo?

**Comment by ashoktelukuntla** [comment]
@treddeni-amazon - I have added maintainers to opensearch-benchmark-workloads

**Comment by krisfreedain** [comment]
thank you @ashoktelukuntla @treddeni-amazon - can you add the following to the end of the new maintainers file (for reference)

[This document](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md) explains what maintainers do in this repo, and how they should be doing it. If you're interested in contributing, see [CONTRIBUTING](https://github.com/opensearch-project/opensearch-plugin-template-java/blob/main/CONTRIBUTING.md).

**Comment by ashoktelukuntla** [comment]
Will get that done and update back

**Comment by CEHENKLE** [comment]
@ashoktelukuntla  Any update?  Thanks!

**Comment by ashoktelukuntla** [comment]
@CEHENKLE - PR raised - review in progress and will merge soon

**Comment by krisfreedain** [comment]
thanks @ashoktelukuntla!
