### ISSUE TITLE
[BUG] OSB is partially broken after the newly added searchable snapshots' tests

### ISSUE THREAD

**Issue by ketanv3** [opensearch-project/opensearch-benchmark-workloads#66]
### What is the bug?
OSB is partially broken after new tests were added for searchable snapshots (https://github.com/opensearch-project/opensearch-benchmark-workloads/commit/ed7b2b6690ac03d5822c9d0f835d7ab90faa7b44) in the 'nyc_taxis' workload.
* [Extra trailing comma](https://github.com/opensearch-project/opensearch-benchmark-workloads/commit/ed7b2b6690ac03d5822c9d0f835d7ab90faa7b44#diff-0721d5ef174f78a809e0b6688ecd8a640a8cf605475c99110c6245d263d5279dR44) is creating a malformed JSON output.
* The 'nyc_taxis' workload uses the `append-no-conflicts` test-procedure by default, but the [recent change](https://github.com/opensearch-project/opensearch-benchmark-workloads/commit/ed7b2b6690ac03d5822c9d0f835d7ab90faa7b44#diff-4d0a6e363206f9ff98683d4c792f453497690185934a96b1de8b0f6b847a04ffR300) has incorrectly marked the `searchable_snapshot` test-procedure as default too, resulting in an error.

### How can one reproduce the bug?

Running `opensearch-benchmark list workloads` command fails with the following error.
```
[ERROR] Cannot list. Could not load '/home/ubuntu/.benchmark/benchmarks/workloads/default/nyc_taxis/workload.json': Expecting property name enclosed in double quotes: line 72 column 5 (char 1740). Lines containing the error:

      "operation-type": "delete-snapshot",
      "repository": "test-repository",
      "snapshot": "test-snapshot",
    },
----^ Error is here
    {
      "name": "create-snapshot",

The complete workload has been written to '/tmp/tmpjevfvc2g.json' for diagnosis.
```

### What is the expected behavior?
Syntax errors should be fixed and workload should define a single test-procedure.

### What is your host/environment?
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1031-aws x86_64)
opensearch-benchmark 0.2.0

**Comment by ketanv3** [comment]
Hi, @tlfeng! Can you take a look at this bug?

**Comment by tlfeng** [comment]
@ketanv3 Sorry for making the trouble, I will address the problem in today. Thanks for pointing out the problems!

**Comment by ketanv3** [comment]
Awesome! @tlfeng

**Comment by tlfeng** [comment]
Thank you for reporting the problem! It has been resolved in the commit https://github.com/opensearch-project/opensearch-benchmark-workloads/commit/d6db98801b6992f61eb031d49b0792fce68c6437 😄
