### ISSUE TITLE
[BUG] Test procedure for searchable snapshots needs backporting and doc updating

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/opensearch-benchmark-workloads#80]
### What is the bug?
Workloads in `main` branch is fetched only when testing against OpenSearch version in `main` branch of OpenSearch repository, which is version 3.x.
If a workload needs to be used for other OpenSearch version, it has to be on the corresponding branches, such as `1` or `2`.
Searchable Snapshots feature is available in OpenSearch 2.4.0, so test procedure for that feature (https://github.com/opensearch-project/opensearch-benchmark-workloads/blob/d5a03d9643f8744c100ce26ab7402c290810c68a/nyc_taxis/test_procedures/seachable-snapshot.json) needs to be backported to branch `2` and `3`.

Update documentation for testing searchable snapshots feature in version 2.7 and above

### How can one reproduce the bug?
run `opensearch-benchmark execute_test --workload=nyc_taxis --test-procedure=searchable_snapshots --distribution-version=2.7.0`

the following error will be shown
`[ERROR] Cannot execute_test. Error in test execution orchestrator (Unknown test_procedure [searchable_snapshots] for workload [nyc_taxis])`
while using the latest OpenSearch build is able to find the testprocedure `opensearch-benchmark execute_test --workload=nyc_taxis --test-procedure=searchable-snapshot ...`

### What is the expected behavior?
Be able to run test procedure `searchable_snapshots` of workload `nyc_taxis` against OpenSearch version 2.7.0 and 3.0.0

### What is your host/environment?
n/a

### Do you have any screenshots?
n/a

### Do you have any additional context?
n/a

**Comment by gkamat** [comment]
We're working on re-organizing the workloads currently, will work this item into that activity.

**Comment by gkamat** [comment]
The change has been backported to the relevant branches and the documentation in the README files should be up to date.  If the feature should appear in the general OSB documentation, please open an issue and/or PR against the OpenSearch doc repository.
