### ISSUE TITLE
[FEATURE] Provide variation of the workload(s) with `unsigned_long` data type

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-benchmark-workloads#85]
### Is your feature request related to a problem?
We've introduced  `unsigned_long` data type support recently to OpenSearch (see please https://github.com/opensearch-project/OpenSearch/issues/2083), but we don't have workloads for benchmarking it yet (those have been run manually by doing ad-hoc index mapping modifications).

### What solution would you like?
Provide variation of the workload(s) with `unsigned_long` data type

### What alternatives have you considered?
Continue with ad-hoc index mapping modifications  

### Do you have any additional context?
See please https://github.com/opensearch-project/OpenSearch/issues/2083, https://github.com/opensearch-project/OpenSearch/issues/8167

**Comment by gashutos** [comment]
@bbarani @gkamat , To add something for `unsigned_long` it will take some time since none of the workload has this data type right now.
But if we can add `total_amount` sort/range queries in `nyc_taxy`, that is `scaled_float` and could be quick to close.

**Comment by reta** [comment]
> But if we can add `total_amount` sort/range queries in `nyc_taxy`, that is `scaled_float` and could be quick to close.

I was thinking in the same vein, but for a `trip_distance`, thank you @gashutos

**Comment by gashutos** [comment]
> > But if we can add `total_amount` sort/range queries in `nyc_taxy`, that is `scaled_float` and could be quick to close.
> 
> 
> 
> I was thinking in the same vein, but for a `trip_distance`, thank you @gashutos 

Yea ! That works too...

**Comment by jordarlu** [comment]
Hi, @IanHoang @rishabh6788 , please have a look and if any comments ... thank you!

**Comment by IanHoang** [comment]
Apologies for the delay. @gashutos feel free to open a PR to add support for this feature in the `nyc_taxis` workload. Please ensure that this change is done in a separate test_procedure file, similar to how `searchable_snapshot` test procedure has its own file in the `nyc_taxis/test_procedures/` directory

**Comment by reta** [comment]
@gashutos I will take care of it, thank you for the hints folks

**Comment by gashutos** [comment]
thanks @reta .
We need for `int` type as well.
#94 
Raised PR for that too.
