### ISSUE TITLE
[FEATURE] Provide sort query with `int` field type in http_logs

### ISSUE THREAD

**Issue by gashutos** [opensearch-project/opensearch-benchmark-workloads#94]
### Is your feature request related to a problem?
After [OpenSearch-6424](https://github.com/opensearch-project/OpenSearch/pull/6424), we added support for sort point based optimization for INT types and we would like to cover that in sort queries.

### What solution would you like?
Add sort query on http_logs's `size` field which is int.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by gkamat** [comment]
This is the [second item listed in this RFC](https://github.com/opensearch-project/opensearch-benchmark/issues/253).  Will append this issue there and add other items to it.
